BoxLayout:
    id: layout
    orientation: 'vertical'
    size: root.size
    
    Camera2:
        id: camera
        resolution: (720,1280)
        play: False
        canvas.before:
            PushMatrix
            Rotate:
                angle: -0
                origin: self.center
        canvas.after:
            PopMatrix
            
    ToggleButton:
        text: 'Play'
        on_press: camera.play = not camera.play
        size_hint_y: None
        height: '48dp'

